# Generated by Django 4.0.1 on 2022-05-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('category', models.CharField(max_length=1000)),
                ('photo', models.ImageField(upload_to='')),
                ('price', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('negotiable', models.BooleanField(default=True)),
            ],
        ),
    ]
