# Generated by Django 4.0.1 on 2022-05-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='orderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller', models.CharField(max_length=1000)),
                ('buyer', models.CharField(max_length=1000)),
                ('products', models.CharField(max_length=1000000000)),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='stockModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('quantity', models.IntegerField()),
                ('buying', models.IntegerField()),
                ('selling', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
